platform :ios, '10.0'
use_frameworks!

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'EightBase'
  pod 'JGProgressHUD'

end
